site_name: Hyper-spectral Imaging Group
site_url: https://wairas.github.io/hsi-website/
site_description: Website for hyper-spectral imaging group at the University of Waikato.
repo_url: https://github.com/wairas/hsi-website
edit_uri: edit/main/docs/
theme:
    name: material
markdown_extensions:
    - toc:
        baselevel: 2
        permalink: "#"
    - attr_list
plugins:
    - search
    # https://github.com/soulless-viewer/mkdocs-video
    - mkdocs-video
    # https://github.com/timvink/mkdocs-table-reader-plugin
    - table-reader
nav:
  - 'Home': index.md
  - 'HAPPy':
      - 'Introduction': happy/index.md
      - 'ADAMS': happy/adams.md
      - 'happy-tools':
        - 'Tools': happy/happy_tools/index.md
        - 'Installation': happy/happy_tools/installation.md
        - 'envi-viewer': happy/happy_tools/envi-viewer.md
        - 'happy-hsi2csv': happy/happy_tools/happy-hsi2csv.md
        - 'happy-hsi2rbg': happy/happy_tools/happy-hsi2rbg.md
        - 'happy-opex2happy': happy/happy_tools/happy-opex2happy.md
      - 'SAM': happy/sam.md
  - 'Publications': publications.md
  - 'People': people.md

